version: '3'
services:
  jvm:
    build:
      context: .
      dockerfile: docker/jvm/Dockerfile
    ports:
      - "8081:8080"
    expose:
      - 8081
    tty: true
  native:
    build:
      context: .
      dockerfile: docker/native/Dockerfile
    ports:
      - "8082:8080"
    expose:
      - 8082
    tty: true
